// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kronecker_tensor_product
Eigen::SparseMatrix<double> kronecker_tensor_product(const Eigen::SparseMatrix<double>& lhs, const Eigen::SparseMatrix<double>& rhs);
RcppExport SEXP _fdaPDE2_kronecker_tensor_product(SEXP lhsSEXP, SEXP rhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type lhs(lhsSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type rhs(rhsSEXP);
    rcpp_result_gen = Rcpp::wrap(kronecker_tensor_product(lhs, rhs));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_cpp_fe_space_lagrange_2_2_1();
RcppExport SEXP _rcpp_module_boot_cpp_fe_space_lagrange_2_3_1();
RcppExport SEXP _rcpp_module_boot_cpp_fe_space_lagrange_3_3_1();
RcppExport SEXP _rcpp_module_boot_cpp_bspline_space();
RcppExport SEXP _rcpp_module_boot_cpp_mesh_1_1();
RcppExport SEXP _rcpp_module_boot_cpp_mesh_1_2();
RcppExport SEXP _rcpp_module_boot_cpp_mesh_2_2();
RcppExport SEXP _rcpp_module_boot_cpp_mesh_2_3();
RcppExport SEXP _rcpp_module_boot_cpp_mesh_3_3();
RcppExport SEXP _rcpp_module_boot_cpp_pde_2_2_1();
RcppExport SEXP _rcpp_module_boot_cpp_pde_3_3_1();
RcppExport SEXP _rcpp_module_boot_SRPDE();

static const R_CallMethodDef CallEntries[] = {
    {"_fdaPDE2_kronecker_tensor_product", (DL_FUNC) &_fdaPDE2_kronecker_tensor_product, 2},
    {"_rcpp_module_boot_cpp_fe_space_lagrange_2_2_1", (DL_FUNC) &_rcpp_module_boot_cpp_fe_space_lagrange_2_2_1, 0},
    {"_rcpp_module_boot_cpp_fe_space_lagrange_2_3_1", (DL_FUNC) &_rcpp_module_boot_cpp_fe_space_lagrange_2_3_1, 0},
    {"_rcpp_module_boot_cpp_fe_space_lagrange_3_3_1", (DL_FUNC) &_rcpp_module_boot_cpp_fe_space_lagrange_3_3_1, 0},
    {"_rcpp_module_boot_cpp_bspline_space", (DL_FUNC) &_rcpp_module_boot_cpp_bspline_space, 0},
    {"_rcpp_module_boot_cpp_mesh_1_1", (DL_FUNC) &_rcpp_module_boot_cpp_mesh_1_1, 0},
    {"_rcpp_module_boot_cpp_mesh_1_2", (DL_FUNC) &_rcpp_module_boot_cpp_mesh_1_2, 0},
    {"_rcpp_module_boot_cpp_mesh_2_2", (DL_FUNC) &_rcpp_module_boot_cpp_mesh_2_2, 0},
    {"_rcpp_module_boot_cpp_mesh_2_3", (DL_FUNC) &_rcpp_module_boot_cpp_mesh_2_3, 0},
    {"_rcpp_module_boot_cpp_mesh_3_3", (DL_FUNC) &_rcpp_module_boot_cpp_mesh_3_3, 0},
    {"_rcpp_module_boot_cpp_pde_2_2_1", (DL_FUNC) &_rcpp_module_boot_cpp_pde_2_2_1, 0},
    {"_rcpp_module_boot_cpp_pde_3_3_1", (DL_FUNC) &_rcpp_module_boot_cpp_pde_3_3_1, 0},
    {"_rcpp_module_boot_SRPDE", (DL_FUNC) &_rcpp_module_boot_SRPDE, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdaPDE2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
