# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kronecker_tensor_product <- function(lhs, rhs) {
    .Call('_fdaPDE2_kronecker_tensor_product', PACKAGE = 'fdaPDE2', lhs, rhs)
}

